Super Admin (DSSK10000001)
array ==
$json_object = array(
			// /*array('title'=>"Dashboard",
				// 'icon'=>"dashboard",
				// 'link'=> "dashboard"),*/
			array(
				'title'=>"Paathshala",
				'icon'=>"globe",
				'link'=> "#",
				'children'=>array(
					array(
						'title'=>"Finance Accounting",
						'icon'=>"credit-card",
						'link'=> "Transaction"),
					array('title'=>"Marketing Telecalling",
						'icon'=>"handshake-o",
						'link'=> "report/call"),
					//array('title'=>"Content Packages",
						// 'icon'=>"database",
						// 'link'=> "Content_packages/view"),
					// array('title'=>"Drive",
						// 'icon'=>"info-circle",
						// 'link'=> "Drive/view"),
					array('title'=>"Business Contacts",
						'icon'=>"address-card-o",
						'link'=> "Business_contact"),
					array('title'=>"CCTV",
						'icon'=>"video-camera",
						'link'=> "CCTV/view"),
					array('title'=>"HR Recruitment",
						'icon'=>"male",
						'link'=> "Hr_recruitment/view"),
					array('title'=>"Masters",
						'icon'=>"cogs",
						'link'=> "settings"),
					array('title'=>"Aabhyas",
						'icon'=>"graduation-cap",
						'link'=> "#",
						'children'=>array(
							array('title'=>"MCQ",
							'icon'=>"question-circle",
							'link'=> "Abhyas_mcq"),
							array('title'=>"PDF",
							'icon'=>"file-pdf-o",
							'link'=> "Abhyas_pdf"),
							array('title'=>"Video",
							'icon'=>"file-video-o",
							'link'=> "Abhyas_video"),
							array('title'=>"Packages",
							'icon'=>"suitcase",
							'link'=> "package")
						),
					),
					array('title'=>"Website",
						'icon'=>"desktop",
						'link'=> "#",
						'children'=>array(
							// array('title'=>"Content Packages",
							// 'icon'=>"database",
							// 'link'=> "Content_packages/view"),
							array('title'=>"Updated Website",
							'icon'=>"sitemap",
							'link'=> "Updated_website/view")
						),
					),//"Masters/view"
				)
			),
			array(
				'title'=>"Thane Paathshala",
				'icon'=>"graduation-cap",
				'link'=> "#",
				'children'=>array(
					array(
						'title'=>"Attendance",
						'icon'=>"check-circle-o",
						'link'=> "Attendance/branchAttendance/BRSK10000001"),
					array('title'=>"Timetable",
						'icon'=>"clock-o",
						'link'=> "batch/show/BRSK10000001"),
					array('title'=>"Students",
						'icon'=>"male",
						'link'=> "#",
						'children'=>array(
							array(
								'title'=>"Students Profile",
								'icon'=>"male",
								'link'=> "student/show/BRSK10000001"),
							array('title'=>"Assignments",
								'icon'=>"briefcase",
								'link'=> "assignment/index/BRSK10000001"),
							array(
								'title'=>"Tests",
								'icon'=>"file-text",
								'link'=> "test/index/BRSK10000001"),
							array('title'=>"Messages",
								'icon'=>"comment",
								'link'=> "student/message/BRSK10000001"),
							array(
								'title'=>"Email",
								'icon'=>"envelope-o",
								'link'=> "student/email/BRSK10000001"),
							array('title'=>"App Notifications",
								'icon'=>"bell",
								'link'=> "student/app_notifications/BRSK10000001"),
							array(
								'title'=>"Student Notice Board",
								'icon'=>"window-restore",
								'link'=> "student_notice/index/BRSK10000001"),
							array('title'=>"Remarks",
								'icon'=>"bars",
								'link'=> "student_remark/index/BRSK10000001"),
							array(
								'title'=>"Chat-Room",
								'icon'=>"comments",
								'link'=> "student/chat_room/BRSK10000001"),
							array('title'=>"Lectures Scheduling & Reporting",
								'icon'=>"external-link-square",
								'link'=> "lecture/show/BRSK10000001"),
							array('title'=>"Parent Meeting",
								'icon'=>"coffee",
								'link'=> "parent_meeting/index/BRSK10000001"),
							array('title'=>"Counselling Session",
								'icon'=>"comments",
								'link'=> "counseling_session/index/BRSK10000001"),
							array('title'=>"Syllabus Coverage",
								'icon'=>"file-text-o",
								'link'=> "syllabus_coverage/index/BRSK10000001"),
							),
						),
					array('title'=>"Professors",
						'icon'=>"book",
						'link'=> "#",
						'children'=>array(
							array('title'=>"List",
								'icon'=>"info-circle",
								'link'=> "team/lists/BRSK10000001"),
							array('title'=>'Doubts',
								'icon'=>'info-circle',
								'link'=>'team/raised_doubts/BRSK10000001'),
							array('title'=>"Tasks",
								'icon'=>"tasks",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Major Tasks",
										'icon'=>"folder-open",
										'link'=> "task/index/BRSK10000001"),
									array('title'=>"Calendar Tasks",
										'icon'=>"calendar",
										'link'=> "task/calendar_task/BRSK10000001")
								),
								),
							array('title'=>"Employee Notice Board",
								'icon'=>"bookmark",
								'link'=> "employee_notice/index/BRSK10000001"),
							array('title'=>"Student Syllabus Coverage",
								'icon'=>"file-text-o",
								'link'=> "syllabus_coverage/students/BRSK10000001"),
							array('title'=>"Reports",
								'icon'=>"flag",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Score",
										'icon'=>"star",
										'link'=> "Report/score/BRSK10000001"),
									array('title'=>"Daily Reports",
										'icon'=>"bar-chart",
										'link'=> "Report/daily_base/BRSK10000001"),
									array('title'=>"Task Reports",
										'icon'=>"flag",
										'link'=> "Report/task_base/BRSK10000001"),
								),
								),
							array('title'=>"Attendance",
								'icon'=>"check-circle",
								'link'=> "team/attendance_veiw/BRSK10000001"),
							array('title'=>"Payments",
								'icon'=>"money",
								'link'=> "team/payment/BRSK10000001"),
							array('title'=>"Awards",
								'icon'=>"trophy", 
								'link'=> "team/award/BRSK10000001")
									),
							),
					array('title'=>"Employees",
						'icon'=>"users",
						'link'=> "#",
						'children'=>array(
							array('title'=>"List",
								'icon'=>"info-circle",
								'link'=> "team/lists/BRSK10000001"),
							// array('title'=>"My Profile",
							// 	'icon'=>"info-circle",
							// 	'link'=> "team/view"),
							array('title'=>"Tasks",
								'icon'=>"tasks",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Major Tasks",
										'icon'=>"folder-open",
										'link'=> "task/index/BRSK10000001"),
									array('title'=>"Calendar Tasks",
										'icon'=>"calendar",
										'link'=> "task/calendar_task/BRSK10000001")
								),
								),
							array('title'=>"Employee Notice Board",
								'icon'=>"bookmark",
								'link'=> "employee_notice/index/BRSK10000001"),
							array('title'=>"Reports",
								'icon'=>"flag",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Score",
										'icon'=>"star",
										'link'=> "Report/score/BRSK10000001"),
									array('title'=>"Daily Reports",
										'icon'=>"bar-chart",
										'link'=> "Report/daily_base/BRSK10000001"),
									array('title'=>"Task Reports",
										'icon'=>"flag",
										'link'=> "Report/task_base/BRSK10000001"),
								),
								),
							array('title'=>"Attendance",
								'icon'=>"check-circle",
								'link'=> "team/attendance_veiw/BRSK10000001"),
							array('title'=>"Payments",
								'icon'=>"money",
								'link'=> "team/payment/BRSK10000001"),
							array('title'=>"Awards",
								'icon'=>"trophy", 
								'link'=> "team/award/BRSK10000001")
									),
						),
					array('title'=>"Center & Inventory",
						'icon'=>"wrench",
						'link'=> "Centerandinventory/view/BRSK10000001"),
					array('title'=>"Finance Accounting",
						'icon'=>"credit-card",
						'link'=> "Transaction/index/BRSK10000001"),
					// array('title'=>"Marketing Telecalling",
					// 	'icon'=>"mobile",
					// 	'link'=> "Marketing_telecalling/view"),
					array('title'=>"Marketing Telecalling",
								'icon'=>"inr",
								'link'=> "#",
								'children'=>array(
									array(
										'title'=>"Add Prospects",
										'icon'=>"phone",
										'link'=> "#",
										'children'=>array(
											array(
												'title'=>"Add Manually",
												'icon'=>"plus",
												'link'=> "lists/add/BRSK10000001",
											),
											array(
												'title'=>"Import Excel",
												'icon'=>"upload",
												'link'=> "lists/import/BRSK10000001",
											)
										)
									),
									array(
										'title'=>"Uploaded Lists",
										'icon'=>"hashtag",
										'link'=> "lists/index/BRSK10000001",
									),
									array(
										'title'=>"Customer",
										'icon'=>"star",
										'link'=> "Customer/show",
									),
									array(
										'title'=>"Leads",
										'icon'=>"address-book",
										'link'=> "leads/index/BRSK10000001",
									),
									array(
										'title'=>"Reports",
										'icon'=>"line-chart",
										'link'=> "report/call/BRSK10000001"
									),
								),
								),
					array('title'=>"Business Contacts",
						'icon'=>"address-book-o",
						'link'=> "Business_contact/transfer/BRSK10000001"),
					array('title'=>"CCTV Thane",
						'icon'=>"video-camera",
						'link'=> "CCTV/view_cam/BRSK10000001")
				)
			),
		);

Branch Development Manager (DSSK10000002)
array ==
$json_object = array(
						'title'=>"Attendance",
						'icon'=>"check-circle-o",
						'link'=> "Attendance/branchAttendance/BRSK10000001"),
					array('title'=>"Timetable",
						'icon'=>"clock-o",
						'link'=> "batch/show/BRSK10000001"),
					array('title'=>"Students",
						'icon'=>"male",
						'link'=> "#",
						'children'=>array(
							array(
								'title'=>"Students Profile",
								'icon'=>"male",
								'link'=> "student/show/BRSK10000001"),
							array('title'=>"Assignments",
								'icon'=>"briefcase",
								'link'=> "assignment/index/BRSK10000001"),
							array(
								'title'=>"Tests",
								'icon'=>"file-text",
								'link'=> "test/index/BRSK10000001"),
							array('title'=>"Messages",
								'icon'=>"comment",
								'link'=> "student/message/BRSK10000001"),
							array(
								'title'=>"Email",
								'icon'=>"envelope-o",
								'link'=> "student/email/BRSK10000001"),
							array('title'=>"App Notifications",
								'icon'=>"bell",
								'link'=> "student/app_notifications/BRSK10000001"),
							array(
								'title'=>"Student Notice Board",
								'icon'=>"window-restore",
								'link'=> "student_notice/index/BRSK10000001"),
							array('title'=>"Remarks",
								'icon'=>"bars",
								'link'=> "student_remark/index/BRSK10000001"),
							array(
								'title'=>"Chat-Room",
								'icon'=>"comments",
								'link'=> "student/chat_room/BRSK10000001"),
							array('title'=>"Lectures Scheduling & Reporting",
								'icon'=>"external-link-square",
								'link'=> "lecture/show/BRSK10000001"),
							array('title'=>"Parent Meeting",
								'icon'=>"coffee",
								'link'=> "parent_meeting/index/BRSK10000001"),
							array('title'=>"Counselling Session",
								'icon'=>"comments",
								'link'=> "counseling_session/index/BRSK10000001"),
							array('title'=>"Syllabus Coverage",
								'icon'=>"file-text-o",
								'link'=> "syllabus_coverage/index/BRSK10000001"),
							),
						),
					array('title'=>"Professors",
						'icon'=>"book",
						'link'=> "#",
						'children'=>array(
							array('title'=>"List",
								'icon'=>"info-circle",
								'link'=> "team/lists/BRSK10000001"),
							array('title'=>'Doubts',
								'icon'=>'info-circle',
								'link'=>'team/raised_doubts/BRSK10000001'),
							array('title'=>"Tasks",
								'icon'=>"tasks",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Major Tasks",
										'icon'=>"folder-open",
										'link'=> "task/index/BRSK10000001"),
									array('title'=>"Calendar Tasks",
										'icon'=>"calendar",
										'link'=> "task/calendar_task/BRSK10000001")
								),
								),
							array('title'=>"Employee Notice Board",
								'icon'=>"bookmark",
								'link'=> "employee_notice/index/BRSK10000001"),
							array('title'=>"Student Syllabus Coverage",
								'icon'=>"file-text-o",
								'link'=> "syllabus_coverage/students/BRSK10000001"),
							array('title'=>"Reports",
								'icon'=>"flag",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Score",
										'icon'=>"star",
										'link'=> "Report/score/BRSK10000001"),
									array('title'=>"Daily Reports",
										'icon'=>"bar-chart",
										'link'=> "Report/daily_base/BRSK10000001"),
									array('title'=>"Task Reports",
										'icon'=>"flag",
										'link'=> "Report/task_base/BRSK10000001"),
								),
								),
							array('title'=>"Attendance",
								'icon'=>"check-circle",
								'link'=> "team/attendance_veiw/BRSK10000001"),
							array('title'=>"Payments",
								'icon'=>"money",
								'link'=> "team/payment/BRSK10000001"),
							array('title'=>"Awards",
								'icon'=>"trophy", 
								'link'=> "team/award/BRSK10000001")
									),
							),
					array('title'=>"Employees",
						'icon'=>"users",
						'link'=> "#",
						'children'=>array(
							array('title'=>"List",
								'icon'=>"info-circle",
								'link'=> "team/lists/BRSK10000001"),
							// array('title'=>"My Profile",
							// 	'icon'=>"info-circle",
							// 	'link'=> "team/view"),
							array('title'=>"Tasks",
								'icon'=>"tasks",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Major Tasks",
										'icon'=>"folder-open",
										'link'=> "task/index/BRSK10000001"),
									array('title'=>"Calendar Tasks",
										'icon'=>"calendar",
										'link'=> "task/calendar_task/BRSK10000001")
								),
								),
							array('title'=>"Employee Notice Board",
								'icon'=>"bookmark",
								'link'=> "employee_notice/index/BRSK10000001"),
							array('title'=>"Reports",
								'icon'=>"flag",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Score",
										'icon'=>"star",
										'link'=> "Report/score/BRSK10000001"),
									array('title'=>"Daily Reports",
										'icon'=>"bar-chart",
										'link'=> "Report/daily_base/BRSK10000001"),
									array('title'=>"Task Reports",
										'icon'=>"flag",
										'link'=> "Report/task_base/BRSK10000001"),
								),
								),
							array('title'=>"Attendance",
								'icon'=>"check-circle",
								'link'=> "team/attendance_veiw/BRSK10000001"),
							array('title'=>"Payments",
								'icon'=>"money",
								'link'=> "team/payment/BRSK10000001"),
							array('title'=>"Awards",
								'icon'=>"trophy", 
								'link'=> "team/award/BRSK10000001")
									),
						),
					array('title'=>"Center & Inventory",
						'icon'=>"wrench",
						'link'=> "Centerandinventory/view/BRSK10000001"),
					array('title'=>"Finance Accounting",
						'icon'=>"credit-card",
						'link'=> "Transaction/index/BRSK10000001"),
					// array('title'=>"Marketing Telecalling",
					// 	'icon'=>"mobile",
					// 	'link'=> "Marketing_telecalling/view"),
					array('title'=>"Marketing Telecalling",
								'icon'=>"inr",
								'link'=> "#",
								'children'=>array(
									array(
										'title'=>"Add Prospects",
										'icon'=>"phone",
										'link'=> "#",
										'children'=>array(
											array(
												'title'=>"Add Manually",
												'icon'=>"plus",
												'link'=> "lists/add/BRSK10000001",
											),
											array(
												'title'=>"Import Excel",
												'icon'=>"upload",
												'link'=> "lists/import/BRSK10000001",
											)
										)
									),
									array(
										'title'=>"Uploaded Lists",
										'icon'=>"hashtag",
										'link'=> "lists/index/BRSK10000001",
									),
									array(
										'title'=>"Customer",
										'icon'=>"star",
										'link'=> "Customer/show",
									),
									array(
										'title'=>"Leads",
										'icon'=>"address-book",
										'link'=> "leads/index/BRSK10000001",
									),
									array(
										'title'=>"Reports",
										'icon'=>"line-chart",
										'link'=> "report/call/BRSK10000001"
									),
								),
								),
					array('title'=>"Business Contacts",
						'icon'=>"address-book-o",
						'link'=> "Business_contact/transfer/BRSK10000001"),
					array('title'=>"CCTV Thane",
						'icon'=>"video-camera",
						'link'=> "CCTV/view_cam/BRSK10000001")
					);

Dean of Department (DSSK10000003)
Array == 
$json_object = array(
			array(
				'title'=>"Thane Paathshala",
				'icon'=>"graduation-cap",
				'link'=> "#",
				'children'=>array(
					array(
						'title'=>"Attendance",
						'icon'=>"check-circle-o",
						'link'=> "Attendance/branchAttendance/BRSK10000001"),
					array('title'=>"Timetable",
						'icon'=>"clock-o",
						'link'=> "batch/show/BRSK10000001"),
					array('title'=>"Students",
						'icon'=>"male",
						'link'=> "#",
						'children'=>array(
							array(
								'title'=>"Students Profile",
								'icon'=>"male",
								'link'=> "student/show/BRSK10000001"),
							array('title'=>"Assignments",
								'icon'=>"briefcase",
								'link'=> "assignment/index/BRSK10000001"),
							array(
								'title'=>"Tests",
								'icon'=>"file-text",
								'link'=> "test/index/BRSK10000001"),
							array('title'=>"Messages",
								'icon'=>"comment",
								'link'=> "student/message/BRSK10000001"),
							array(
								'title'=>"Email",
								'icon'=>"envelope-o",
								'link'=> "student/email/BRSK10000001"),
							array('title'=>"App Notifications",
								'icon'=>"bell",
								'link'=> "student/app_notifications/BRSK10000001"),
							array(
								'title'=>"Student Notice Board",
								'icon'=>"window-restore",
								'link'=> "student_notice/index/BRSK10000001"),
							array('title'=>"Remarks",
								'icon'=>"bars",
								'link'=> "student_remark/index/BRSK10000001"),
							array(
								'title'=>"Chat-Room",
								'icon'=>"comments",
								'link'=> "student/chat_room/BRSK10000001"),
							array('title'=>"Lectures Scheduling & Reporting",
								'icon'=>"external-link-square",
								'link'=> "lecture/show/BRSK10000001"),
							array('title'=>"Parent Meeting",
								'icon'=>"coffee",
								'link'=> "parent_meeting/index/BRSK10000001"),
							array('title'=>"Counselling Session",
								'icon'=>"comments",
								'link'=> "counseling_session/index/BRSK10000001"),
							array('title'=>"Syllabus Coverage",
								'icon'=>"file-text-o",
								'link'=> "syllabus_coverage/index/BRSK10000001"),
							),
						),
					array('title'=>"Professors",
						'icon'=>"book",
						'link'=> "#",
						'children'=>array(
							array('title'=>"List",
								'icon'=>"info-circle",
								'link'=> "team/lists/BRSK10000001"),
							array('title'=>'Doubts',
								'icon'=>'info-circle',
								'link'=>'team/raised_doubts/BRSK10000001'),
							array('title'=>"Tasks",
								'icon'=>"tasks",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Major Tasks",
										'icon'=>"folder-open",
										'link'=> "task/index/BRSK10000001"),
									array('title'=>"Calendar Tasks",
										'icon'=>"calendar",
										'link'=> "task/calendar_task/BRSK10000001")
								),
								),
							array('title'=>"Employee Notice Board",
								'icon'=>"bookmark",
								'link'=> "employee_notice/index/BRSK10000001"),
							array('title'=>"Student Syllabus Coverage",
								'icon'=>"file-text-o",
								'link'=> "syllabus_coverage/students/BRSK10000001"),
							array('title'=>"Reports",
								'icon'=>"flag",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Score",
										'icon'=>"star",
										'link'=> "Report/score/BRSK10000001"),
									array('title'=>"Daily Reports",
										'icon'=>"bar-chart",
										'link'=> "Report/daily_base/BRSK10000001"),
									array('title'=>"Task Reports",
										'icon'=>"flag",
										'link'=> "Report/task_base/BRSK10000001"),
								),
								),
							array('title'=>"Attendance",
								'icon'=>"check-circle",
								'link'=> "team/attendance_veiw/BRSK10000001"),
							array('title'=>"Payments",
								'icon'=>"money",
								'link'=> "team/payment/BRSK10000001"),
							array('title'=>"Awards",
								'icon'=>"trophy", 
								'link'=> "team/award/BRSK10000001")
									),
							),
					array('title'=>"Employees",
						'icon'=>"users",
						'link'=> "#",
						'children'=>array(
							array('title'=>"List",
								'icon'=>"info-circle",
								'link'=> "team/lists/BRSK10000001"),
							// array('title'=>"My Profile",
							// 	'icon'=>"info-circle",
							// 	'link'=> "team/view"),
							array('title'=>"Tasks",
								'icon'=>"tasks",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Major Tasks",
										'icon'=>"folder-open",
										'link'=> "task/index/BRSK10000001"),
									array('title'=>"Calendar Tasks",
										'icon'=>"calendar",
										'link'=> "task/calendar_task/BRSK10000001")
								),
								),
							array('title'=>"Employee Notice Board",
								'icon'=>"bookmark",
								'link'=> "employee_notice/index/BRSK10000001"),
							array('title'=>"Reports",
								'icon'=>"flag",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Score",
										'icon'=>"star",
										'link'=> "Report/score/BRSK10000001"),
									array('title'=>"Daily Reports",
										'icon'=>"bar-chart",
										'link'=> "Report/daily_base/BRSK10000001"),
									array('title'=>"Task Reports",
										'icon'=>"flag",
										'link'=> "Report/task_base/BRSK10000001"),
								),
								),
							array('title'=>"Attendance",
								'icon'=>"check-circle",
								'link'=> "team/attendance_veiw/BRSK10000001"),
							array('title'=>"Payments",
								'icon'=>"money",
								'link'=> "team/payment/BRSK10000001"),
							array('title'=>"Awards",
								'icon'=>"trophy", 
								'link'=> "team/award/BRSK10000001")
									),
						),
					array('title'=>"Center & Inventory",
						'icon'=>"wrench",
						'link'=> "Centerandinventory/view/BRSK10000001"),
					array('title'=>"Finance Accounting",
						'icon'=>"credit-card",
						'link'=> "Transaction/index/BRSK10000001"),
					// array('title'=>"Marketing Telecalling",
					// 	'icon'=>"mobile",
					// 	'link'=> "Marketing_telecalling/view"),
					array('title'=>"Marketing Telecalling",
								'icon'=>"inr",
								'link'=> "#",
								'children'=>array(
									array(
										'title'=>"Add Prospects",
										'icon'=>"phone",
										'link'=> "#",
										'children'=>array(
											array(
												'title'=>"Add Manually",
												'icon'=>"plus",
												'link'=> "lists/add/BRSK10000001",
											),
											array(
												'title'=>"Import Excel",
												'icon'=>"upload",
												'link'=> "lists/import/BRSK10000001",
											)
										)
									),
									array(
										'title'=>"Uploaded Lists",
										'icon'=>"hashtag",
										'link'=> "lists/index/BRSK10000001",
									),
									array(
										'title'=>"Customer",
										'icon'=>"star",
										'link'=> "Customer/show",
									),
									array(
										'title'=>"Leads",
										'icon'=>"address-book",
										'link'=> "leads/index/BRSK10000001",
									),
									array(
										'title'=>"Reports",
										'icon'=>"line-chart",
										'link'=> "report/call/BRSK10000001"
									),
								),
								),
					array('title'=>"Business Contacts",
						'icon'=>"address-book-o",
						'link'=> "Business_contact/transfer/BRSK10000001"),
					array('title'=>"CCTV Thane",
						'icon'=>"video-camera",
						'link'=> "CCTV/view_cam/BRSK10000001")
				)
			),
		);

Branch Admin (DSSK10000004)
Array == 
$json_object = array(
			array(
				'title'=>"Thane Paathshala",
				'icon'=>"graduation-cap",
				'link'=> "#",
				'children'=>array(
					array(
						'title'=>"Attendance",
						'icon'=>"check-circle-o",
						'link'=> "Attendance/branchAttendance/BRSK10000001"),
					array('title'=>"Timetable",
						'icon'=>"clock-o",
						'link'=> "batch/show/BRSK10000001"),
					array('title'=>"Students",
						'icon'=>"male",
						'link'=> "#",
						'children'=>array(
							array(
								'title'=>"Students Profile",
								'icon'=>"male",
								'link'=> "student/show/BRSK10000001"),
							array('title'=>"Assignments",
								'icon'=>"briefcase",
								'link'=> "assignment/index/BRSK10000001"),
							array(
								'title'=>"Tests",
								'icon'=>"file-text",
								'link'=> "test/index/BRSK10000001"),
							array('title'=>"Messages",
								'icon'=>"comment",
								'link'=> "student/message/BRSK10000001"),
							array(
								'title'=>"Email",
								'icon'=>"envelope-o",
								'link'=> "student/email/BRSK10000001"),
							array('title'=>"App Notifications",
								'icon'=>"bell",
								'link'=> "student/app_notifications/BRSK10000001"),
							array(
								'title'=>"Student Notice Board",
								'icon'=>"window-restore",
								'link'=> "student_notice/index/BRSK10000001"),
							array('title'=>"Remarks",
								'icon'=>"bars",
								'link'=> "student_remark/index/BRSK10000001"),
							array(
								'title'=>"Chat-Room",
								'icon'=>"comments",
								'link'=> "student/chat_room/BRSK10000001"),
							array('title'=>"Lectures Scheduling & Reporting",
								'icon'=>"external-link-square",
								'link'=> "lecture/show/BRSK10000001"),
							array('title'=>"Parent Meeting",
								'icon'=>"coffee",
								'link'=> "parent_meeting/index/BRSK10000001"),
							array('title'=>"Counselling Session",
								'icon'=>"comments",
								'link'=> "counseling_session/index/BRSK10000001"),
							array('title'=>"Syllabus Coverage",
								'icon'=>"file-text-o",
								'link'=> "syllabus_coverage/index/BRSK10000001"),
							),
						),
					array('title'=>"Professors",
						'icon'=>"book",
						'link'=> "#",
						'children'=>array(
							array('title'=>"List",
								'icon'=>"info-circle",
								'link'=> "team/lists/BRSK10000001"),
							array('title'=>'Doubts',
								'icon'=>'info-circle',
								'link'=>'team/raised_doubts/BRSK10000001'),
							array('title'=>"Tasks",
								'icon'=>"tasks",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Major Tasks",
										'icon'=>"folder-open",
										'link'=> "task/index/BRSK10000001"),
									array('title'=>"Calendar Tasks",
										'icon'=>"calendar",
										'link'=> "task/calendar_task/BRSK10000001")
								),
								),
							array('title'=>"Employee Notice Board",
								'icon'=>"bookmark",
								'link'=> "employee_notice/index/BRSK10000001"),
							array('title'=>"Student Syllabus Coverage",
								'icon'=>"file-text-o",
								'link'=> "syllabus_coverage/students/BRSK10000001"),
							array('title'=>"Reports",
								'icon'=>"flag",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Score",
										'icon'=>"star",
										'link'=> "Report/score/BRSK10000001"),
									array('title'=>"Daily Reports",
										'icon'=>"bar-chart",
										'link'=> "Report/daily_base/BRSK10000001"),
									array('title'=>"Task Reports",
										'icon'=>"flag",
										'link'=> "Report/task_base/BRSK10000001"),
								),
								),
							array('title'=>"Attendance",
								'icon'=>"check-circle",
								'link'=> "team/attendance_veiw/BRSK10000001"),
							array('title'=>"Payments",
								'icon'=>"money",
								'link'=> "team/payment/BRSK10000001"),
							array('title'=>"Awards",
								'icon'=>"trophy", 
								'link'=> "team/award/BRSK10000001")
									),
							),
					array('title'=>"Employees",
						'icon'=>"users",
						'link'=> "#",
						'children'=>array(
							array('title'=>"List",
								'icon'=>"info-circle",
								'link'=> "team/lists/BRSK10000001"),
							// array('title'=>"My Profile",
							// 	'icon'=>"info-circle",
							// 	'link'=> "team/view"),
							array('title'=>"Tasks",
								'icon'=>"tasks",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Major Tasks",
										'icon'=>"folder-open",
										'link'=> "task/index/BRSK10000001"),
									array('title'=>"Calendar Tasks",
										'icon'=>"calendar",
										'link'=> "task/calendar_task/BRSK10000001")
								),
								),
							array('title'=>"Employee Notice Board",
								'icon'=>"bookmark",
								'link'=> "employee_notice/index/BRSK10000001"),
							array('title'=>"Reports",
								'icon'=>"flag",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Score",
										'icon'=>"star",
										'link'=> "Report/score/BRSK10000001"),
									array('title'=>"Daily Reports",
										'icon'=>"bar-chart",
										'link'=> "Report/daily_base/BRSK10000001"),
									array('title'=>"Task Reports",
										'icon'=>"flag",
										'link'=> "Report/task_base/BRSK10000001"),
								),
								),
							array('title'=>"Attendance",
								'icon'=>"check-circle",
								'link'=> "team/attendance_veiw/BRSK10000001"),
							array('title'=>"Payments",
								'icon'=>"money",
								'link'=> "team/payment/BRSK10000001"),
							array('title'=>"Awards",
								'icon'=>"trophy", 
								'link'=> "team/award/BRSK10000001")
									),
						),
					array('title'=>"Center & Inventory",
						'icon'=>"wrench",
						'link'=> "Centerandinventory/view/BRSK10000001"),
					array('title'=>"Business Contacts",
						'icon'=>"address-book-o",
						'link'=> "Business_contact/transfer/BRSK10000001"),
					array('title'=>"CCTV Thane",
						'icon'=>"video-camera",
						'link'=> "CCTV/view_cam/BRSK10000001")
				)
			),
		);

Marketing Manager (DSSK10000006)
array ==
$json_object =array(
				'title'=>"Paathshala",
				'icon'=>"globe",
				'link'=> "#",
				'children'=>array(
					array('title'=>"Marketing Telecalling",
						'icon'=>"handshake-o",
						'link'=> "report/call"),
					)
				),
				array(
				'title'=>"Thane Paathshala",
				'icon'=>"graduation-cap",
				'link'=> "#",
					array('title'=>"Marketing Telecalling",
						'icon'=>"mobile",
						'link'=> "Marketing_telecalling/view"),
					array('title'=>"Marketing Telecalling",
								'icon'=>"inr",
								'link'=> "#",
								'children'=>array(
									array(
										'title'=>"Add Prospects",
										'icon'=>"phone",
										'link'=> "#",
										'children'=>array(
											array(
												'title'=>"Add Manually",
												'icon'=>"plus",
												'link'=> "lists/add/BRSK10000001",
											),
											array(
												'title'=>"Import Excel",
												'icon'=>"upload",
												'link'=> "lists/import/BRSK10000001",
											)
										)
									)
									)
								)
					)
);

Telecaller (DSSK10000007)
array ==
$json_object =array(
					array('title'=>"Marketing Telecalling",
						'icon'=>"mobile",
						'link'=> "Marketing_telecalling/view"),
					array('title'=>"Marketing Telecalling",
								'icon'=>"inr",
								'link'=> "#",
								'children'=>array(
									array(
										'title'=>"Add Prospects",
										'icon'=>"phone",
										'link'=> "#",
										'children'=>array(
											array(
												'title'=>"Add Manually",
												'icon'=>"plus",
												'link'=> "lists/add/BRSK10000001",
											),
											array(
												'title'=>"Import Excel",
												'icon'=>"upload",
												'link'=> "lists/import/BRSK10000001",
											)
										)
									)
									)
								)
					)
);

Telecaller (DSSK10000008)
array ==
$json_object = array(
					array('title'=>"List",
					'icon'=>"info-circle",
					'link'=> "team/lists/BRSK10000001"),
);


Faculty (DSSK10000009)
array ==
$json_object =array('title'=>"Students",
						'icon'=>"male",
						'link'=> "#",
						'children'=>array(
							array(
								'title'=>"Students Profile",
								'icon'=>"male",
								'link'=> "student/show/BRSK10000001"),
							array('title'=>"Assignments",
								'icon'=>"briefcase",
								'link'=> "assignment/index/BRSK10000001"),
							array(
								'title'=>"Tests",
								'icon'=>"file-text",
								'link'=> "test/index/BRSK10000001"),
							array('title'=>"Messages",
								'icon'=>"comment",
								'link'=> "student/message/BRSK10000001"),
							array(
								'title'=>"Email",
								'icon'=>"envelope-o",
								'link'=> "student/email/BRSK10000001"),
							array('title'=>"App Notifications",
								'icon'=>"bell",
								'link'=> "student/app_notifications/BRSK10000001"),
							array(
								'title'=>"Student Notice Board",
								'icon'=>"window-restore",
								'link'=> "student_notice/index/BRSK10000001"),
							array('title'=>"Remarks",
								'icon'=>"bars",
								'link'=> "student_remark/index/BRSK10000001"),
							array(
								'title'=>"Chat-Room",
								'icon'=>"comments",
								'link'=> "student/chat_room/BRSK10000001"),
							array('title'=>"Lectures Scheduling & Reporting",
								'icon'=>"external-link-square",
								'link'=> "lecture/show/BRSK10000001"),
							array('title'=>"Parent Meeting",
								'icon'=>"coffee",
								'link'=> "parent_meeting/index/BRSK10000001"),
							array('title'=>"Counselling Session",
								'icon'=>"comments",
								'link'=> "counseling_session/index/BRSK10000001"),
							array('title'=>"Syllabus Coverage",
								'icon'=>"file-text-o",
								'link'=> "syllabus_coverage/index/BRSK10000001"),
							),
						)
);

Marketing Executive (DSSK10000010)
array ==
$json_object =array(
					array('title'=>"Marketing Telecalling",
						'icon'=>"mobile",
						'link'=> "Marketing_telecalling/view"),
					array('title'=>"Marketing Telecalling",
								'icon'=>"inr",
								'link'=> "#",
								'children'=>array(
									array(
										'title'=>"Add Prospects",
										'icon'=>"phone",
										'link'=> "#",
										'children'=>array(
											array(
												'title'=>"Add Manually",
												'icon'=>"plus",
												'link'=> "lists/add/BRSK10000001",
											),
											array(
												'title'=>"Import Excel",
												'icon'=>"upload",
												'link'=> "lists/import/BRSK10000001",
											)
										)
									)
									)
								)
					)
);

Student (DSSK10000011)
Array == 
$json_object = array(
							array('title'=>"Aabhyas",
								'icon'=>"font",
								'link'=> "abhyas_entry"),		
							array('title'=>"Syllabus Coverage",
								'icon'=>"file-text-o",
								'link'=> "syllabus_coverage/index/BRSK10000001"),
							array('title'=>"Lectures Scheduling & Reporting",
								'icon'=>"external-link-square",
								'link'=> "lecture/show/BRSK10000001"),
							array('title'=>"Assignments",
								'icon'=>"briefcase",
								'link'=> "assignment/index/BRSK10000001"),
							array(
								'title'=>"Tests",
								'icon'=>"file-text",
								'link'=> "test/index/BRSK10000001"),
							array(
								'title'=>"Student Notice Board",
								'icon'=>"window-restore",
								'link'=> "student_notice/index/BRSK10000001"),
							array(
								'title'=>"Chats",
								'icon'=>"comments",
								'link'=> "student/chat_room/BRSK10000001"),
							array('title'=>"Messages",
								'icon'=>"comment",
								'link'=> "student/message/BRSK10000001"),
							array(
								'title'=>"Email",
								'icon'=>"envelope-o",
								'link'=> "student/email/BRSK10000001"),
							array('title'=>"App Notifications",
								'icon'=>"bell",
								'link'=> "student/app_notifications/BRSK10000001"),
							array('title'=>"Remarks",
								'icon'=>"bars",
								'link'=> "student_remark/index/BRSK10000001"),
							array('title'=>"Parent Meeting",
								'icon'=>"coffee",
								'link'=> "parent_meeting/index/BRSK10000001"),
							array('title'=>"My Counselling Session",
								'icon'=>"comments",
								'link'=> "counseling_session/index/BRSK10000001"),
		);


Parent (DSSK10000012)
Array == 
$json_object = array(
							array('title'=>"Syllabus Coverage",
								'icon'=>"file-text-o",
								'link'=> "syllabus_coverage/index/BRSK10000001"),
							array('title'=>"Lectures Scheduling & Reporting",
								'icon'=>"external-link-square",
								'link'=> "lecture/show/BRSK10000001"),
							array('title'=>"Assignments",
								'icon'=>"briefcase",
								'link'=> "assignment/index/BRSK10000001"),
							array(
								'title'=>"Tests",
								'icon'=>"file-text",
								'link'=> "test/index/BRSK10000001"),
							array(
								'title'=>"Student Notice Board",
								'icon'=>"window-restore",
								'link'=> "student_notice/index/BRSK10000001"),
							array(
								'title'=>"Chats",
								'icon'=>"comments",
								'link'=> "student/chat_room/BRSK10000001"),
							array('title'=>"Messages",
								'icon'=>"comment",
								'link'=> "student/message/BRSK10000001"),
							array(
								'title'=>"Email",
								'icon'=>"envelope-o",
								'link'=> "student/email/BRSK10000001"),
							array('title'=>"App Notifications",
								'icon'=>"bell",
								'link'=> "student/app_notifications/BRSK10000001"),
							array('title'=>"Remarks",
								'icon'=>"bars",
								'link'=> "student_remark/index/BRSK10000001"),
							array('title'=>"Parent Meeting",
								'icon'=>"coffee",
								'link'=> "parent_meeting/index/BRSK10000001"),
							array('title'=>"My Counselling Session",
								'icon'=>"comments",
								'link'=> "counseling_session/index/BRSK10000001"),
		);

Vice President (DSSK10000013)
Array == 
$json_object = array(
			array(
				'title'=>"Thane Paathshala",
				'icon'=>"graduation-cap",
				'link'=> "#",
				'children'=>array(
					array(
						'title'=>"Attendance",
						'icon'=>"check-circle-o",
						'link'=> "Attendance/branchAttendance/BRSK10000001"),
					array('title'=>"Timetable",
						'icon'=>"clock-o",
						'link'=> "batch/show/BRSK10000001"),
					array('title'=>"Students",
						'icon'=>"male",
						'link'=> "#",
						'children'=>array(
							array(
								'title'=>"Students Profile",
								'icon'=>"male",
								'link'=> "student/show/BRSK10000001"),
							array('title'=>"Assignments",
								'icon'=>"briefcase",
								'link'=> "assignment/index/BRSK10000001"),
							array(
								'title'=>"Tests",
								'icon'=>"file-text",
								'link'=> "test/index/BRSK10000001"),
							array('title'=>"Messages",
								'icon'=>"comment",
								'link'=> "student/message/BRSK10000001"),
							array(
								'title'=>"Email",
								'icon'=>"envelope-o",
								'link'=> "student/email/BRSK10000001"),
							array('title'=>"App Notifications",
								'icon'=>"bell",
								'link'=> "student/app_notifications/BRSK10000001"),
							array(
								'title'=>"Student Notice Board",
								'icon'=>"window-restore",
								'link'=> "student_notice/index/BRSK10000001"),
							array('title'=>"Remarks",
								'icon'=>"bars",
								'link'=> "student_remark/index/BRSK10000001"),
							array(
								'title'=>"Chat-Room",
								'icon'=>"comments",
								'link'=> "student/chat_room/BRSK10000001"),
							array('title'=>"Lectures Scheduling & Reporting",
								'icon'=>"external-link-square",
								'link'=> "lecture/show/BRSK10000001"),
							array('title'=>"Parent Meeting",
								'icon'=>"coffee",
								'link'=> "parent_meeting/index/BRSK10000001"),
							array('title'=>"Counselling Session",
								'icon'=>"comments",
								'link'=> "counseling_session/index/BRSK10000001"),
							array('title'=>"Syllabus Coverage",
								'icon'=>"file-text-o",
								'link'=> "syllabus_coverage/index/BRSK10000001"),
							),
						),
					array('title'=>"Professors",
						'icon'=>"book",
						'link'=> "#",
						'children'=>array(
							array('title'=>"List",
								'icon'=>"info-circle",
								'link'=> "team/lists/BRSK10000001"),
							array('title'=>'Doubts',
								'icon'=>'info-circle',
								'link'=>'team/raised_doubts/BRSK10000001'),
							array('title'=>"Tasks",
								'icon'=>"tasks",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Major Tasks",
										'icon'=>"folder-open",
										'link'=> "task/index/BRSK10000001"),
									array('title'=>"Calendar Tasks",
										'icon'=>"calendar",
										'link'=> "task/calendar_task/BRSK10000001")
								),
								),
							array('title'=>"Employee Notice Board",
								'icon'=>"bookmark",
								'link'=> "employee_notice/index/BRSK10000001"),
							array('title'=>"Student Syllabus Coverage",
								'icon'=>"file-text-o",
								'link'=> "syllabus_coverage/students/BRSK10000001"),
							array('title'=>"Reports",
								'icon'=>"flag",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Score",
										'icon'=>"star",
										'link'=> "Report/score/BRSK10000001"),
									array('title'=>"Daily Reports",
										'icon'=>"bar-chart",
										'link'=> "Report/daily_base/BRSK10000001"),
									array('title'=>"Task Reports",
										'icon'=>"flag",
										'link'=> "Report/task_base/BRSK10000001"),
								),
								),
							array('title'=>"Attendance",
								'icon'=>"check-circle",
								'link'=> "team/attendance_veiw/BRSK10000001"),
							array('title'=>"Payments",
								'icon'=>"money",
								'link'=> "team/payment/BRSK10000001"),
							array('title'=>"Awards",
								'icon'=>"trophy", 
								'link'=> "team/award/BRSK10000001")
									),
							),
					array('title'=>"Employees",
						'icon'=>"users",
						'link'=> "#",
						'children'=>array(
							array('title'=>"List",
								'icon'=>"info-circle",
								'link'=> "team/lists/BRSK10000001"),
							// array('title'=>"My Profile",
							// 	'icon'=>"info-circle",
							// 	'link'=> "team/view"),
							array('title'=>"Tasks",
								'icon'=>"tasks",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Major Tasks",
										'icon'=>"folder-open",
										'link'=> "task/index/BRSK10000001"),
									array('title'=>"Calendar Tasks",
										'icon'=>"calendar",
										'link'=> "task/calendar_task/BRSK10000001")
								),
								),
							array('title'=>"Employee Notice Board",
								'icon'=>"bookmark",
								'link'=> "employee_notice/index/BRSK10000001"),
							array('title'=>"Reports",
								'icon'=>"flag",
								'link'=> "#",
								'children'=>array(
									array('title'=>"Score",
										'icon'=>"star",
										'link'=> "Report/score/BRSK10000001"),
									array('title'=>"Daily Reports",
										'icon'=>"bar-chart",
										'link'=> "Report/daily_base/BRSK10000001"),
									array('title'=>"Task Reports",
										'icon'=>"flag",
										'link'=> "Report/task_base/BRSK10000001"),
								),
								),
							array('title'=>"Attendance",
								'icon'=>"check-circle",
								'link'=> "team/attendance_veiw/BRSK10000001"),
							array('title'=>"Payments",
								'icon'=>"money",
								'link'=> "team/payment/BRSK10000001"),
							array('title'=>"Awards",
								'icon'=>"trophy", 
								'link'=> "team/award/BRSK10000001")
									),
						),
					array('title'=>"Center & Inventory",
						'icon'=>"wrench",
						'link'=> "Centerandinventory/view/BRSK10000001"),
					array('title'=>"Finance Accounting",
						'icon'=>"credit-card",
						'link'=> "Transaction/index/BRSK10000001"),
					// array('title'=>"Marketing Telecalling",
					// 	'icon'=>"mobile",
					// 	'link'=> "Marketing_telecalling/view"),
					array('title'=>"Marketing Telecalling",
								'icon'=>"inr",
								'link'=> "#",
								'children'=>array(
									array(
										'title'=>"Add Prospects",
										'icon'=>"phone",
										'link'=> "#",
										'children'=>array(
											array(
												'title'=>"Add Manually",
												'icon'=>"plus",
												'link'=> "lists/add/BRSK10000001",
											),
											array(
												'title'=>"Import Excel",
												'icon'=>"upload",
												'link'=> "lists/import/BRSK10000001",
											)
										)
									),
									array(
										'title'=>"Uploaded Lists",
										'icon'=>"hashtag",
										'link'=> "lists/index/BRSK10000001",
									),
									array(
										'title'=>"Customer",
										'icon'=>"star",
										'link'=> "Customer/show",
									),
									array(
										'title'=>"Leads",
										'icon'=>"address-book",
										'link'=> "leads/index/BRSK10000001",
									),
									array(
										'title'=>"Reports",
										'icon'=>"line-chart",
										'link'=> "report/call/BRSK10000001"
									),
								),
								),
					array('title'=>"Business Contacts",
						'icon'=>"address-book-o",
						'link'=> "Business_contact/transfer/BRSK10000001"),
					array('title'=>"CCTV Thane",
						'icon'=>"video-camera",
						'link'=> "CCTV/view_cam/BRSK10000001")
				)
			),
		);




